site_name: Manual de Políticas LACNIC
site_description: Manual de Políticas de LACNIC
site_author: Ariel Weher
copyright: Copyright LACNIC
repo_name: 'GitHub'
site_url: https://manual.lacnic.net/
repo_url: http://github.com/aweher/manual-lacnic
edit_uri: edit/main/docs/
#dev_addr: '0.0.0.0:8000'

theme:
  icon:
    repo: fontawesome/brands/github
  locale: es
  language: es
  prev_next_buttons_location: none
  analytics:
  gtag: 
  name: material
  features:
    - content.code.annotate
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - search.suggest
    - search.highlight
    - search.share
#    - header.autohide
  font:
    text: Barlow
  palette:
  - primary: deep orange
  - accent: orange
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Cambiar al modo oscuro
  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Cambiar al modo claro

nav:
    - Inicio: 'index.md'
    - Resumen: 'manual/resumen/'
    - 1 Definiciones: 'manual/seccion1/'
    - 2 Direcciones IPv4: 'manual/seccion2/'
    - 3 Distribución de ASN: 'manual/seccion3/'
    - 4 Distribución y Asignación IPv6: 'manual/seccion4/'
    - 5 Delegación de Resolución Inversa: 'manual/seccion5/'
    - 6 Política de LAME Delegation: 'manual/seccion6/'
    - 7 Revocación y Devolución de Recursos: 'manual/seccion7/'
    - 8 Solicitud de Bulk WHOIS: 'manual/seccion8/'
    - 9 Políticas Globales: 'manual/seccion9/'
    - 10 Distribución de Recursos para Investigación y Experimentación: 'manual/seccion10/'
    - 11 Políticas sobre el agotamiento IPv4: 'manual/seccion11/'
    - 12 Validación del abuse-c y abuse-mailbox: 'manual/seccion12/'
    - A Apendices: 'manual/apendices'
    - B Referencias: 'manual/referencias'

markdown_extensions:
    - toc:
        permalink: "#"
    - pymdownx.highlight:
        #linenums: true
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.superfences
    - pymdownx.snippets
    - pymdownx.details
    - pymdownx.tabbed
    - abbr
    - admonition
    - attr_list
    - def_list
    - footnotes
    - meta
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde

plugins:
  - search
  - git-revision-date
  - git-revision-date-localized
  - macros

extra:
  generator: false
  analytics:
    provider: google
    property: XYZ
  consent:
    title: Cookies
    description: > 
      Usamos cookies para reconocer sus visitas y preferencias repetidas, así como para medir la efectividad de nuestra documentación y si los usuarios encuentran lo que están buscando. Con su consentimiento, nos está ayudando a mejorar nuestra documentación.
#  social:
#    - icon: fontawesome/solid/ambulance
#      link: https://lacnic.net
#      name: LACNIC
